.
.TH "LKERNEL" "1" "August 2021" "Copyright 2021 Under Kux Software License" "LKernel Family Manual"
.
.SH "NAME"
\fBlkernel\fR \- A Lua\-based (OS Kernel\-Inspired) interface which aids in interacting with certain libraries and hardwares\.
.
.SH "DESCRIPTION"
An \fBlkernel(1)\fR is a processing unit designed to run certain applications (daemons) in order to help Lua interaction with certain software or hardware\.
.
.P
LKernel at it\'s core must be implemented\. LKernels are not specified to one certain software, they can be written to support multiple software features & designs\.
.
.P
LKernels were originally introduced in 2021 by the Kux project when Kai Gonzalez decided to implement a modular interface written in lua, for interacting with Kux software\.
.
.P
This project contains (1) basic LKernel which is extendable and contains all the basic features for any LKernel out there\.
.
.SH "SEE ALSO"
FreeKSD \fIhttps://thekaigonzalez\.github\.io/MissingManPages/man1/ksd\.1\.html\fR
.
.P
KuxNE \fIhttps://thekaigonzalez\.github\.io/MissingManPages/man1/kuxne\.1\.html\fR
.
.P
LKernel [OLD] \fIhttps://thekaigonzalez\.github\.io/MissingManPages/man1/lkernel\.1\.html\fR
