
.
.TH "LKUXKERNEL" "1" "August 2021" "" ""
.
.SH "NAME"
\fBlkuxkernel\fR \- A Root LKernel for writing programs on the Kux platform\.
.
.SH "DESCRIPTION"
The LKuxKernel is a LKernel which contains a lua library, and some core features to get you started on your LKernel development\.
.
.P
An \fBLKernel\fR (see lkernel(1)) is a Lua 5\.4\-5\.3 interface which helps with interacting with certain software / hardware features\.
.
.P
LKernels are implemented in such a way which allows users to be able to reproduce an LKernel in a couple of simple steps, without any external dependencies\.
.
.P
The LKernel needs a frontend to run on the screen, and handles most of the backends for you\.
.
.P
for other Projects, Kux Kernels are used for anything, they\'re just backends for many different Lua Operations\.
.
.SH "SEE ALSO"
lkernel(1)
